---
# tasks file for pip

- name: check pip version
  shell: "{{ pip_bin }} --version"
  register: pip_check
  ignore_errors: yes
  changed_when: no

- name: check pip latest
  set_fact:
    pip_latest: "{{ lookup('pypi_version', 'pip') }}"

- block:
  - name: download get-pip.py
    get_url:
      url: "{{ pip_download_url }}"
      dest: "{{ pip_install_path }}"

  - name: install pip
    command: "{{ python_bin }} {{ pip_install_path }}/get-pip.py{{ ' --proxy={}'.format(pip_proxy_url) if pip_proxy_url else '' }}"

  - name: remove get-pip.py
    file:
      state: absent
      path: "{{ pip_install_path }}/get-pip.py"
  when: pip_check.rc != 0

- name: update pip package
  pip:
    name: pip
    version: "{{ pip_version | default(pip_latest, true) }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ pip_packages }}"