---
# tasks file for pip
- block:
  - name: check python version
    shell: "{{ python_bin }} --version 2>&1"
    register: python_check
    ignore_errors: yes
    changed_when: no

  - name: get python version
    set_fact:
      python_version: "{{ python_check.stdout.split(' ')[1] }}"

  - name: set pip path
    set_fact:
      pip_bin_path: "{{ pip_bin }}"
    when: python_version is version('2.0.0', '>=') and python_version is version('3', '<')

  - name: set pip3 path
    set_fact:
      pip_bin_path: "{{ pip3_bin }}"
    when: python_version is version('3.0.0', '>=')

  - name: check pip exists
    stat:
      path: "{{ pip_bin_path }}"
    register: pip_bin_check

  - name: check pip version
    shell: "{{ pip_bin_path }} --version"
    register: pip_version_check
    ignore_errors: yes
    changed_when: no

  - block:
    - name: download get-pip.py
      get_url:
        url: "{{ pip_download_url }}"
        dest: "{{ pip_install_path }}"

    - name: install pip
      command: "{{ python_bin }} {{ pip_install_path }}/get-pip.py{{ ' --proxy={}'.format(pip_proxy_url) if pip_proxy_url else '' }}"

    - name: remove get-pip.py
      file:
        state: absent
        path: "{{ pip_install_path }}/get-pip.py"
    when: not pip_bin_check.stat.exists or pip_version_check.rc != 0

  - name: check pip latest
    set_fact:
      pip_latest: "{{ lookup('pypi_version', 'pip') }}"

  - name: update pip package
    pip:
      name: pip
      version: "{{ pip_version | default(pip_latest, true) }}"

  - name: Install pip packages
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version | d(omit) }}"
      requirements: "{{ item.requirements | d(omit) }}"
      virtualenv: "{{ item.virtualenv | d(omit) }}"
      virtualenv_python: "{{ item.virtualenv_python | d(omit) }}"
      virtualenv_command: "{{ item.virtualenv_command | d(omit) }}"
      virtualenv_site_packages: "{{ item.virtualenv_site_packages | d(omit) }}"
    loop: "{{ pip_packages }}"
  when: not skip_dependencies